### ISSUE TITLE
Index file for content types is ordered differently on different platforms

### ISSUE THREAD

**Issue by Glenruben** [ItemConsulting/xp-codegen-plugin#44]
regarding .xp-codegen/site/content-types/index.d.ts
On windows the element in the file is ordered alphabetically
on Mac OS at least, it is ordered by some other logic. 
Here is an example of a committ with no other changes than ordering, between one system and another. 
https://github.com/statisticsnorway/mimir/commit/f84664cf9f10d50ac244020e8e85bd9e849c2364

**Comment by tajakobsen** [comment]
I see that the commit you shared uses **xp-codegen-plugin@2.1.0**. We released a fix to this last week in the **2.2.0** release

**Comment by tajakobsen** [comment]
@Glenruben Could you upgrade to 2.2.0, and confirm that the issue has been fixed?

**Comment by Glenruben** [comment]
Can confirm that this fixed the issue! Thank you!
